server:
  port: 8080
  servlet:
    context-path: /api

spring:
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on-save
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
