server:
  port: 8080
  servlet:
    context-path: /api
    session:
      tracking-modes: cookie
      cookie:
        name: SESSION-ID
        max-age: 1m
        http-only: true
        secure: true
        path: /
        same-site: none
      timeout: 1m

spring:
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
